package com.example.databindinginandroid;

import android.app.Activity;
import android.os.Bundle;
import android.provider.ContactsContract;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.databinding.DataBindingUtil;

import com.example.databindinginandroid.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity {

    private ActivityMainBinding activityMainBinding;  // this is the name of binding class generated by data binding library
//    ActivityMainBinding is object or class of data binding library

    private MyClickHandler myClickHandler;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);

        Person p1=new Person("jack","jack@gmail.com");

        activityMainBinding = DataBindingUtil.setContentView(this,R.layout.activity_main);
//         This method is use to set the content of View of an activity to the specified layout resource.


        activityMainBinding.setPerson(p1);


//        Binding the handler for click events
        myClickHandler=new MyClickHandler(this);
        activityMainBinding.setClickhandler(myClickHandler);


//        Two Way Binding


    }
}


//In build.gradle.kts ---> in android tag section   use this
//  buildFeatures{
//        dataBinding=true
//    }



/*

Two way data binding is the process of binding your objects to your XML layouts so that layout can send data to your binding objects.

 */


/*
    in Android data binding library the @={} is use to enable two way binding


 */